import {
  Booking,
  MedicalDocument,
  Provider,
} from "./types";

// All data below simulates what a real backend (PostGIS-backed API,
// AI vision service, booking service) would return. Nothing here is
// computed by real business logic on the client — it is static fixture
// data standing in for network responses.

export const MOCK_PROVIDERS: Provider[] = [
  {
    id: "prov-01",
    name: "Greenfield Veterinary Hospital",
    category: "vet",
    lat: 28.4744,
    lng: 77.5040,
    distanceKm: 1.2,
    address: "12 Sector Alpha-1, Greater Noida",
    phone: "+91 98110 22334",
    rating: 4.8,
    reviewCount: 214,
    openNow: true,
    is24x7: false,
    verified: true,
    speciesHandled: ["dog", "cat", "bird"],
    hours: [
      { day: "Mon–Fri", open: "9:00 AM", close: "8:00 PM", isToday: true },
      { day: "Saturday", open: "9:00 AM", close: "6:00 PM" },
      { day: "Sunday", open: "10:00 AM", close: "2:00 PM" },
    ],
    tags: ["Surgery", "Dental", "Grooming"],
    photoTone: "sage",
    aboutText:
      "A full-service small-animal hospital with an in-house lab and digital X-ray, run by Dr. Meera Kapoor and a team of four vets.",
    reviews: [
      {
        id: "rev-01",
        author: "Ananya S.",
        rating: 5,
        comment: "Handled my dog's leg fracture with real care. Clear updates the whole time.",
        date: "2026-08-02",
        petType: "dog",
      },
      {
        id: "rev-02",
        author: "Rohit M.",
        rating: 4,
        comment: "Good doctors, waiting room gets busy on weekends.",
        date: "2026-07-18",
        petType: "cat",
      },
      {
        id: "rev-03",
        author: "Fatima K.",
        rating: 5,
        comment: "Gentle with nervous cats. My cat actually let them check her ears.",
        date: "2026-06-30",
        petType: "cat",
      },
    ],
  },
  {
    id: "prov-02",
    name: "PawCare 24/7 Emergency Clinic",
    category: "clinic24",
    lat: 28.4680,
    lng: 77.5100,
    distanceKm: 2.4,
    address: "Plot 7, Knowledge Park III, Greater Noida",
    phone: "+91 98110 88221",
    rating: 4.6,
    reviewCount: 356,
    openNow: true,
    is24x7: true,
    verified: true,
    speciesHandled: ["dog", "cat", "exotic"],
    hours: [{ day: "Every day", open: "12:00 AM", close: "11:59 PM", isToday: true }],
    tags: ["Trauma", "ICU", "Night Shift Vets"],
    photoTone: "clay",
    aboutText:
      "Open around the clock with a dedicated ICU and on-call surgeon rota. First point of contact for after-hours crises.",
    reviews: [
      {
        id: "rev-04",
        author: "Devika R.",
        rating: 5,
        comment: "Came in at 3am with a bloated dog, they were ready before we arrived.",
        date: "2026-08-10",
        petType: "dog",
      },
      {
        id: "rev-05",
        author: "Sameer P.",
        rating: 4,
        comment: "Expensive but you're paying for the 24-hour availability.",
        date: "2026-07-05",
      },
    ],
    hasTraumaCenter: true,
    ambulanceEta: 9,
  },
  {
    id: "prov-03",
    name: "Companion Animal Ambulance Unit 4",
    category: "ambulance",
    lat: 28.4790,
    lng: 77.4990,
    distanceKm: 0.8,
    address: "Dispatch base — Sector Omega, Greater Noida",
    phone: "+91 90112 44110",
    rating: 4.9,
    reviewCount: 88,
    openNow: true,
    is24x7: true,
    verified: true,
    speciesHandled: ["dog", "cat", "livestock", "exotic"],
    hours: [{ day: "Every day", open: "12:00 AM", close: "11:59 PM", isToday: true }],
    tags: ["Oxygen Support", "Stretcher", "Paramedic Onboard"],
    photoTone: "amber",
    aboutText: "Rapid-response ambulance unit equipped for stabilization en route to the nearest trauma center.",
    reviews: [],
    ambulanceEta: 6,
  },
  {
    id: "prov-04",
    name: "City Street Animal Ambulance",
    category: "ambulance",
    lat: 28.4700,
    lng: 77.5180,
    distanceKm: 3.1,
    address: "Dispatch base — NH-24 Service Road",
    phone: "+91 90112 77009",
    rating: 4.5,
    reviewCount: 41,
    openNow: true,
    is24x7: true,
    verified: true,
    speciesHandled: ["dog", "cat"],
    hours: [{ day: "Every day", open: "12:00 AM", close: "11:59 PM", isToday: true }],
    tags: ["Human & Animal Accidents", "First Responder"],
    photoTone: "sand",
    aboutText: "Covers both street-accident casualties and injured strays across the eastern zone.",
    reviews: [],
    ambulanceEta: 13,
  },
  {
    id: "prov-05",
    name: "Sunrise Trauma & Surgical Center",
    category: "clinic24",
    lat: 28.4820,
    lng: 77.5090,
    distanceKm: 2.0,
    address: "Sector Beta-2 Main Road, Greater Noida",
    phone: "+91 98110 55231",
    rating: 4.7,
    reviewCount: 172,
    openNow: true,
    is24x7: true,
    verified: true,
    speciesHandled: ["dog", "cat", "livestock"],
    hours: [{ day: "Every day", open: "12:00 AM", close: "11:59 PM", isToday: true }],
    tags: ["Trauma", "Orthopedic Surgery", "Blood Bank"],
    photoTone: "sage",
    aboutText: "Regional trauma referral center with an on-site blood bank for transfusions.",
    reviews: [
      {
        id: "rev-06",
        author: "Karan V.",
        rating: 5,
        comment: "Saved our dog after a hit-and-run. Cannot thank the surgical team enough.",
        date: "2026-05-22",
        petType: "dog",
      },
    ],
    hasTraumaCenter: true,
    ambulanceEta: 11,
  },
  {
    id: "prov-06",
    name: "Second Chance Street Animal NGO",
    category: "ngo",
    lat: 28.4650,
    lng: 77.4950,
    distanceKm: 2.7,
    address: "Community Center, Sector Gamma-3",
    phone: "+91 98110 90012",
    rating: 4.9,
    reviewCount: 63,
    openNow: true,
    is24x7: false,
    verified: true,
    speciesHandled: ["dog", "cat"],
    hours: [{ day: "Mon–Sat", open: "8:00 AM", close: "7:00 PM", isToday: true }],
    tags: ["Free Sterilization", "Stray Rescue", "Fostering"],
    photoTone: "amber",
    aboutText: "Volunteer-run rescue and sterilization drive covering the eastern colonies. Free pickup for injured strays.",
    reviews: [
      {
        id: "rev-07",
        author: "Priya N.",
        rating: 5,
        comment: "They picked up an injured stray within 40 minutes of my call.",
        date: "2026-06-11",
      },
    ],
  },
  {
    id: "prov-07",
    name: "Dr. Arvind Bhatia — House-Call Vet",
    category: "vet",
    lat: 28.4770,
    lng: 77.4910,
    distanceKm: 1.8,
    address: "Visits within 5km of Sector Alpha",
    phone: "+91 98100 33421",
    rating: 4.4,
    reviewCount: 97,
    openNow: false,
    is24x7: false,
    verified: true,
    speciesHandled: ["dog", "cat", "bird", "exotic"],
    hours: [
      { day: "Mon–Sat", open: "10:00 AM", close: "1:00 PM", isToday: true },
      { day: "Mon–Sat (evening)", open: "5:00 PM", close: "9:00 PM" },
    ],
    tags: ["House Calls", "Exotic Pets", "Vaccination"],
    photoTone: "sand",
    aboutText: "Independent practitioner specializing in exotic pets and stress-free home visits for senior animals.",
    reviews: [
      {
        id: "rev-08",
        author: "Neha T.",
        rating: 4,
        comment: "Great with my parrot, though booking a slot takes a day or two.",
        date: "2026-07-29",
        petType: "bird",
      },
    ],
  },
];

export const MOCK_DOCUMENTS: MedicalDocument[] = [
  {
    id: "doc-01",
    petName: "Bruno",
    kind: "lab_report",
    title: "Complete Blood Count",
    status: "parsed",
    uploadedAt: "2026-09-02T10:14:00Z",
    sourceFileName: "bruno_cbc_scan.jpg",
    aiSummary:
      "Most values sit inside the canine reference range. White blood cell count is mildly elevated, which can indicate a minor infection or stress response — worth a follow-up if it persists.",
    flaggedCount: 1,
    metrics: [
      { id: "m1", label: "White Blood Cells", value: "16.8", unit: "×10⁹/L", referenceRange: "6.0 – 15.0", flag: "high" },
      { id: "m2", label: "Red Blood Cells", value: "6.4", unit: "×10¹²/L", referenceRange: "5.5 – 8.5", flag: "normal" },
      { id: "m3", label: "Hemoglobin", value: "15.1", unit: "g/dL", referenceRange: "12.0 – 18.0", flag: "normal" },
      { id: "m4", label: "Platelets", value: "310", unit: "×10⁹/L", referenceRange: "200 – 500", flag: "normal" },
    ],
    vaccines: [],
  },
  {
    id: "doc-02",
    petName: "Bruno",
    kind: "vaccination",
    title: "Vaccination Record",
    status: "parsed",
    uploadedAt: "2026-07-14T09:02:00Z",
    sourceFileName: "vaccine_card_bruno.jpg",
    aiSummary:
      "Core vaccines are current. The Rabies booster becomes due in the coming weeks — a reminder has been added to the timeline.",
    flaggedCount: 1,
    metrics: [],
    vaccines: [
      { id: "v1", vaccine: "Rabies", dateAdministered: "2025-09-20", nextDueDate: "2026-09-20", status: "due_soon" },
      { id: "v2", vaccine: "DHPP", dateAdministered: "2026-01-11", nextDueDate: "2027-01-11", status: "up_to_date" },
      { id: "v3", vaccine: "Bordetella", dateAdministered: "2025-12-02", nextDueDate: "2026-06-02", status: "overdue" },
    ],
  },
  {
    id: "doc-03",
    petName: "Momo",
    kind: "prescription",
    title: "Handwritten Prescription",
    status: "parsed",
    uploadedAt: "2026-08-27T15:40:00Z",
    sourceFileName: "momo_prescription.jpg",
    aiSummary:
      "Prescribed a 7-day course of amoxicillin for a skin infection. Dosage transcribed from handwriting — please confirm with your vet if the photo was unclear.",
    flaggedCount: 0,
    metrics: [
      { id: "m5", label: "Amoxicillin Dosage", value: "125", unit: "mg twice daily", referenceRange: "As prescribed", flag: "normal" },
    ],
    vaccines: [],
  },
  {
    id: "doc-04",
    petName: "Momo",
    kind: "lab_report",
    title: "Feline Metabolic Panel",
    status: "needs_review",
    uploadedAt: "2026-09-10T08:20:00Z",
    sourceFileName: "momo_panel_blurry.jpg",
    aiSummary:
      "Two fields on this scan were too blurred to read with confidence. The rest of the panel has been extracted below — a clearer photo would help confirm the flagged fields.",
    flaggedCount: 2,
    metrics: [
      { id: "m6", label: "Creatinine", value: "2.4", unit: "mg/dL", referenceRange: "0.8 – 2.1", flag: "high" },
      { id: "m7", label: "BUN", value: "—", unit: "mg/dL", referenceRange: "16 – 36", flag: "critical" },
      { id: "m8", label: "Glucose", value: "98", unit: "mg/dL", referenceRange: "70 – 150", flag: "normal" },
    ],
    vaccines: [],
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: "bk-01",
    providerId: "prov-01",
    providerName: "Greenfield Veterinary Hospital",
    petName: "Bruno",
    date: "2026-09-18",
    time: "5:30 PM",
    reason: "Annual checkup + Rabies booster",
    status: "confirmed",
  },
  {
    id: "bk-02",
    providerId: "prov-07",
    providerName: "Dr. Arvind Bhatia — House-Call Vet",
    petName: "Momo",
    date: "2026-09-22",
    time: "11:00 AM",
    reason: "Follow-up on skin infection",
    status: "pending",
  },
];

export const CATEGORY_META: Record<
  Provider["category"],
  { label: string; shortLabel: string }
> = {
  vet: { label: "Veterinarians", shortLabel: "Vets" },
  clinic24: { label: "24/7 Clinics", shortLabel: "24/7 Clinics" },
  ambulance: { label: "Ambulances", shortLabel: "Ambulances" },
  ngo: { label: "NGOs & Shelters", shortLabel: "NGOs" },
};
